project:
  type: website
  output-dir: docs

website:
  title: "Kyle Suelflow"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: projects.qmd
        text: Projects
      - href: tidytuesday.qmd
        text: Tidy Tuesday
  page-footer:
    left: |
      &copy; Kyle Suelflow, 2023<br>
      All content licensed under <i class='bi-badge-cc'></i>
      [(CC BY-NC-SA 4.0)](http://creativecommons.org/licenses/by-nc-sa/4.0/)
    right: |
      Site built with <a href='https://quarto.org/'>Quarto</a>



format:
  html:
    theme: zephyr
    css: styles.css
    toc: true

editor: visual

